import { ColDef } from 'ag-grid-enterprise';

// Simplified column definitions based on columns.md
// Only including the field and headerName for the main columns (not the nested "Garda", "Risk", etc.)
// Note: Using colId and valueGetter because the data structure uses dot notation in field names
export const columnDefs: ColDef[] = [
  { field: 'accrual_effect', headerName: 'Accrual Effect' },
  { colId: 'Book.Activity', headerName: 'Activity', valueGetter: (params) => params.data?.['Book.Activity'] },
  { colId: 'Product.adjusted_maturity_date', headerName: 'Adjusted Maturity Date', valueGetter: (params) => params.data?.['Product.adjusted_maturity_date'] },
  { colId: 'Product.adjusted_premium', headerName: 'Adjusted Premium', valueGetter: (params) => params.data?.['Product.adjusted_premium'] },
  { colId: 'Product.bbg_ticker', headerName: 'BBG Ticker', valueGetter: (params) => params.data?.['Product.bbg_ticker'] },
  { colId: 'Book.BeginLivePricing', headerName: 'BeginLivePricing', valueGetter: (params) => params.data?.['Book.BeginLivePricing'] },
  { colId: 'Product.security_cusip', headerName: 'CUSIP', valueGetter: (params) => params.data?.['Product.security_cusip'] },
  { colId: 'Book.Category', headerName: 'Category', valueGetter: (params) => params.data?.['Book.Category'] },
  { field: 'change_quote_close', headerName: 'Change in Close Quote' },
  { field: 'change_nominal', headerName: 'Change in Nominal' },
  { field: 'quote_close', headerName: 'Close Quote' },
  { colId: 'Book.Code', headerName: 'Code', valueGetter: (params) => params.data?.['Book.Code'] },
  { colId: 'Product.executing_party', headerName: 'Counter Party', valueGetter: (params) => params.data?.['Product.executing_party'] },
  { colId: 'Product.currency', headerName: 'Currency', valueGetter: (params) => params.data?.['Product.currency'] },
  { colId: 'Book.DeltaHedgeFlag', headerName: 'DeltaHedgeFlag', valueGetter: (params) => params.data?.['Book.DeltaHedgeFlag'] },
  { colId: 'Book.DominantCountry', headerName: 'Dominant Country', valueGetter: (params) => params.data?.['Book.DominantCountry'], rowGroup: true },
  { field: 'end_nominal', headerName: 'End Nominal' },
  { field: 'end_price', headerName: 'End Price' },
  { field: 'end_quantity', headerName: 'End Quantity' },
  { field: 'end_quote', headerName: 'End Quote' },
  { field: 'end_settlement_amount', headerName: 'End Settlement Amount' },
  { colId: 'Book.Entity', headerName: 'Entity', valueGetter: (params) => params.data?.['Book.Entity'] },
  { colId: 'Book.Fund', headerName: 'Fund', valueGetter: (params) => params.data?.['Book.Fund'] },
  { field: 'fx_pl_effect', headerName: 'FxPLEffect' },
  { field: 'fx_pl_effect_close', headerName: 'FxPLEffect Close' },
  { colId: 'Book.CountryRegion', headerName: 'Geography', valueGetter: (params) => params.data?.['Book.CountryRegion'], rowGroup: true },
  { field: 'has_strategy_position_changes', headerName: 'Has Position Changes' },
  { colId: 'Product.security_isin', headerName: 'ISIN', valueGetter: (params) => params.data?.['Product.security_isin'] },
  { colId: 'Product.index_family', headerName: 'Index Family', valueGetter: (params) => params.data?.['Product.index_family'] },
  { colId: 'Product.index_series', headerName: 'Index Series', valueGetter: (params) => params.data?.['Product.index_series'] },
  { colId: 'Product.index_tenor', headerName: 'Index Tenor', valueGetter: (params) => params.data?.['Product.index_tenor'] },
  { field: 'life_cycle_pl', headerName: 'Life Cycle Effect' },
  { colId: 'Product.maturity_date', headerName: 'Maturity Date', valueGetter: (params) => params.data?.['Product.maturity_date'] },
  { colId: 'Book.Name', headerName: 'Name', valueGetter: (params) => params.data?.['Book.Name'] },
  { colId: 'Book.OTLivePxable', headerName: 'OTLivePxAble', valueGetter: (params) => params.data?.['Book.OTLivePxable'] },
  { colId: 'Product.option_strike', headerName: 'Option Strike', valueGetter: (params) => params.data?.['Product.option_strike'] },
  { colId: 'Product.option_type', headerName: 'Option Type', valueGetter: (params) => params.data?.['Product.option_type'] },
  { field: 'pl_base_after_close', headerName: 'PL Base After Close', aggFunc: 'sum' },
  { field: 'pl_base_ccy', headerName: 'PL Base Ccy', aggFunc: 'sum' },
  { field: 'pl_base_close', headerName: 'PL Base Close', aggFunc: 'sum' },
  { field: 'pl_close', headerName: 'PL Close', aggFunc: 'sum' },
  { field: 'pl_base', headerName: 'PL Daily', aggFunc: 'sum' },
  { field: 'pl_latest', headerName: 'PL Latest', aggFunc: 'sum' },
  { colId: 'Product.premium', headerName: 'Premium', valueGetter: (params) => params.data?.['Product.premium'] },
  { colId: 'Product.premium_currency', headerName: 'Premium Currency', valueGetter: (params) => params.data?.['Product.premium_currency'] },
  { colId: 'Product.premium_date', headerName: 'Premium Date', valueGetter: (params) => params.data?.['Product.premium_date'] },
  { colId: 'Product.processing_type', headerName: 'Processing Type', valueGetter: (params) => params.data?.['Product.processing_type'] },
  { field: 'prod_id', headerName: 'Prod Id' },
  { colId: 'Product.category', headerName: 'Product Category', valueGetter: (params) => params.data?.['Product.category'] },
  { colId: 'Product.product_type', headerName: 'Product Type', valueGetter: (params) => params.data?.['Product.product_type'] },
  { colId: 'Book.RecapGroup', headerName: 'Recap Group', valueGetter: (params) => params.data?.['Book.RecapGroup'], rowGroup: true },
  { colId: 'Book.ReportingGroup', headerName: 'Reporting Group', valueGetter: (params) => params.data?.['Book.ReportingGroup'] },
  { colId: 'Book.RiskPod', headerName: 'Risk Pod', valueGetter: (params) => params.data?.['Book.RiskPod'] },
  { colId: 'Product.security_default_ticker', headerName: 'Security Default Ticker', valueGetter: (params) => params.data?.['Product.security_default_ticker'] },
  { field: 'start_nominal', headerName: 'Start Nominal' },
  { field: 'start_price', headerName: 'Start Price' },
  { field: 'start_quantity', headerName: 'Start Quantity' },
  { field: 'start_quote', headerName: 'Start Quote' },
  { colId: 'Book.Strategy', headerName: 'Strategy', valueGetter: (params) => params.data?.['Book.Strategy'], rowGroup: true },
  { colId: 'Book.SubActivity', headerName: 'SubActivity', valueGetter: (params) => params.data?.['Book.SubActivity'] },
  { colId: 'Book.SubCategory', headerName: 'SubCategory', valueGetter: (params) => params.data?.['Book.SubCategory'] },
  { colId: 'Book.SubTheme', headerName: 'SubTheme', valueGetter: (params) => params.data?.['Book.SubTheme'] },
  { colId: 'Book.Theme', headerName: 'Theme', valueGetter: (params) => params.data?.['Book.Theme'] },
  { colId: 'Product.trade_date', headerName: 'Trade Date', valueGetter: (params) => params.data?.['Product.trade_date'] },
  { field: 'trade_id', headerName: 'Trade Id' },
  { colId: 'Product.trade_type', headerName: 'Trade Type', valueGetter: (params) => params.data?.['Product.trade_type'] },
  { field: 'trader', headerName: 'Trader' },
  { colId: 'Product.underlier_info', headerName: 'Underlier Info', valueGetter: (params) => params.data?.['Product.underlier_info'] },
  { colId: 'Book.UnderlyingCommodity', headerName: 'Underlying Commodity', valueGetter: (params) => params.data?.['Book.UnderlyingCommodity'] },
];
